name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: drupal
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Code standards
      run: vendor/bin/phpcs web/modules/custom

    - name: Unit tests
      working-directory: web/core
      run: ../../vendor/bin/phpunit --group=test --testsuite=unit

    - name: Kernel tests
      working-directory: web/core
      env:
        SIMPLETEST_BASE_URL: http://localhost
        SIMPLETEST_DB: mysql://root:secret@127.0.0.1/drupal
      run: ../../vendor/bin/phpunit --group=test --testsuite=kernel
