name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Start containers
      run: docker-compose -f docker-compose.ci.yml up -d --build

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Code standards
      run: vendor/bin/phpcs web/modules/custom

    - name: Unit tests
      run: docker-compose exec -T -w /var/www/html/web/core drupal ../../vendor/bin/phpunit --group=test --testsuite=unit

    - name: Kernel tests
      run: docker-compose exec -T -w /var/www/html/web/core drupal ../../vendor/bin/phpunit --group=test --testsuite=kernel

    - name: Functional tests
      run: docker-compose exec -T -w /var/www/html/web/core drupal ../../vendor/bin/phpunit --group=test --testsuite=functional
