name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Start containers
      run: docker-compose up -d --build

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Code standards
      run: vendor/bin/phpcs web/modules/custom

    - name: Unit tests
      working-directory: web/core
      run: ../../vendor/bin/phpunit --group=test --testsuite=unit

    - name: Kernel tests
      working-directory: web/core
      env:
        SIMPLETEST_BASE_URL: http://localhost
        SIMPLETEST_DB: mysql://root:secret@127.0.0.1/drupal
      run: ../../vendor/bin/phpunit --group=test --testsuite=kernel

    - name: Functional tests
      working-directory: web/core
      env:
        SIMPLETEST_BASE_URL: http://localhost
        SIMPLETEST_DB: mysql://root:secret@127.0.0.1 }}/drupal
      run: ../../vendor/bin/phpunit --group=test --testsuite=functional
