name: Update Drupal core

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Start containers
      run: docker-compose -f docker-compose.ci.yml up -d --build

    - name: Install dependencies
      run: docker-compose exec -T -w /var/www/html drupal composer install --prefer-dist --no-progress --no-suggest

    - name: Install Drupal
      run: docker-compose exec -T -w /var/www/html drupal vendor/bin/drush site:install --existing-config -y

    - name: Check homepage
      run: curl http://localhost

    - name: Ensure sites/default is writeable
      run: docker-compose exec -T -w /var/www/html chmod u+w web/sites/default

    - name: Update Drupal core
      run: docker-compose exec -T -w /var/www/html drupal composer update drupal/core-recommended drupal/core-dev --with-dependencies --prefer-dist --no-progress --no-suggest

    - name: Update database
      run: docker-compose exec -T -w /var/www/html drupal vendor/bin/drush updb -y

    - name: Export configuration
      run: docker-compose exec -T -w /var/www/html drupal vendor/bin/drush cex -y

    - name: Check homepage
      run: curl http://localhost

    - name: Create pull request
      uses: peter-evans/create-pull-request@v2
      with:
        commit-message: Update Drupal core
        title: Update Drupal core
        branch: chore/update-drupal-core
